# Generated by Django 3.0.8 on 2021-02-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('logo', models.ImageField(upload_to='website/logo')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
