# Generated by Django 3.0.8 on 2021-04-16 08:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', ckeditor.fields.RichTextField(max_length=100)),
                ('mail_address', ckeditor.fields.RichTextField(max_length=100)),
                ('comment', ckeditor.fields.RichTextField(max_length=2000)),
                ('news_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.News')),
            ],
        ),
    ]
