# Generated by Django 3.0.8 on 2021-04-23 17:10

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_hashtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('message', ckeditor.fields.RichTextField(max_length=2000)),
                ('posted_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
