# Generated by Django 3.0.8 on 2021-04-27 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingPoll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=2000)),
                ('total_votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PollOptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=100)),
                ('num_of_votes', models.IntegerField(default=0)),
                ('voting_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.VotingPoll')),
            ],
        ),
    ]
