# Generated by Django 3.0.8 on 2021-04-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='location',
            field=models.CharField(choices=[('H-970*90', 'H-970*90'), ('S1-150*150', 'S1-150*150'), ('S2-150*150', 'S2-150*150')], max_length=20),
        ),
    ]
